FROM golang:1.24-alpine AS base

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /main cmd/proxy/main.go

FROM gcr.io/distroless/static-debian11

# Copy the binary and necessary files for the user
COPY --from=base /main .

EXPOSE 8080

CMD ["./main"]
